apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{.Release.Name}}-svc
  name: {{.Release.Name}}-svc
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: {{.Release.Name}}-back
  type: NodePort
~                                                                                                                                                                            
~                         
